package grigoreva.facesmanager.data.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import grigoreva.facesmanager.data.greendao.Person;
import grigoreva.facesmanager.data.greendao.Photo;

import grigoreva.facesmanager.data.greendao.PersonDao;
import grigoreva.facesmanager.data.greendao.PhotoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig photoDaoConfig;

    private final PersonDao personDao;
    private final PhotoDao photoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Photo.class, photoDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

}
