package grigoreva.facesmanager.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.util.List;
import java.util.Map;

import grigoreva.facesmanager.data.greendao.customtype.LandmarkType;

/**
 * Entity mapped to table "PERSON_PHOTO".
 */
public class PersonPhoto {

    private Long id;
    private String photoUrl;
    private Long personId;
    private Float faceWidth;
    private Float faceHeight;
    private Float normalFaceWidth;
    private Float normalFaceHeight;
    private Integer avgFaceColor;

    // KEEP FIELDS - put your custom fields here
    private Map<LandmarkType, PhotoLandmark> landmarkList;
    // KEEP FIELDS END

    public PersonPhoto() {
    }

    public PersonPhoto(Long id) {
        this.id = id;
    }

    public PersonPhoto(Long id, String photoUrl, Long personId, Float faceWidth, Float faceHeight, Float normalFaceWidth, Float normalFaceHeight, Integer avgFaceColor) {
        this.id = id;
        this.photoUrl = photoUrl;
        this.personId = personId;
        this.faceWidth = faceWidth;
        this.faceHeight = faceHeight;
        this.normalFaceWidth = normalFaceWidth;
        this.normalFaceHeight = normalFaceHeight;
        this.avgFaceColor = avgFaceColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public Long getPersonId() {
        return personId;
    }

    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    public Float getFaceWidth() {
        return faceWidth;
    }

    public void setFaceWidth(Float faceWidth) {
        this.faceWidth = faceWidth;
    }

    public Float getFaceHeight() {
        return faceHeight;
    }

    public void setFaceHeight(Float faceHeight) {
        this.faceHeight = faceHeight;
    }

    public Float getNormalFaceWidth() {
        return normalFaceWidth;
    }

    public void setNormalFaceWidth(Float normalFaceWidth) {
        this.normalFaceWidth = normalFaceWidth;
    }

    public Float getNormalFaceHeight() {
        return normalFaceHeight;
    }

    public void setNormalFaceHeight(Float normalFaceHeight) {
        this.normalFaceHeight = normalFaceHeight;
    }

    public Integer getAvgFaceColor() {
        return avgFaceColor;
    }

    public void setAvgFaceColor(Integer avgFaceColor) {
        this.avgFaceColor = avgFaceColor;
    }

    // KEEP METHODS - put your custom methods here
    public void setLandmarkList(Map<LandmarkType, PhotoLandmark> landmarkList) {
        this.landmarkList = landmarkList;
    }

    public Map<LandmarkType, PhotoLandmark> getLandmarkList() {
        return landmarkList;
    }
    // KEEP METHODS END

}
