package grigoreva.facesmanager.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_PHOTO".
 */
public class PersonPhoto {

    private Long id;
    private String photoUrl;
    private Float faceWidth;
    private Float faceHeight;
    private Float normalFaceWidth;
    private Float normalFaceHeight;
    private Integer avgFaceColor;

    public PersonPhoto() {
    }

    public PersonPhoto(Long id) {
        this.id = id;
    }

    public PersonPhoto(Long id, String photoUrl, Float faceWidth, Float faceHeight, Float normalFaceWidth, Float normalFaceHeight, Integer avgFaceColor) {
        this.id = id;
        this.photoUrl = photoUrl;
        this.faceWidth = faceWidth;
        this.faceHeight = faceHeight;
        this.normalFaceWidth = normalFaceWidth;
        this.normalFaceHeight = normalFaceHeight;
        this.avgFaceColor = avgFaceColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public Float getFaceWidth() {
        return faceWidth;
    }

    public void setFaceWidth(Float faceWidth) {
        this.faceWidth = faceWidth;
    }

    public Float getFaceHeight() {
        return faceHeight;
    }

    public void setFaceHeight(Float faceHeight) {
        this.faceHeight = faceHeight;
    }

    public Float getNormalFaceWidth() {
        return normalFaceWidth;
    }

    public void setNormalFaceWidth(Float normalFaceWidth) {
        this.normalFaceWidth = normalFaceWidth;
    }

    public Float getNormalFaceHeight() {
        return normalFaceHeight;
    }

    public void setNormalFaceHeight(Float normalFaceHeight) {
        this.normalFaceHeight = normalFaceHeight;
    }

    public Integer getAvgFaceColor() {
        return avgFaceColor;
    }

    public void setAvgFaceColor(Integer avgFaceColor) {
        this.avgFaceColor = avgFaceColor;
    }

}
