package grigoreva.facesmanager.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PHOTO".
 */
public class Photo {

    private Long id;
    private String photoUrl;
    private Float noiseX;
    private Float noiseY;
    private Float leftEyesX;
    private Float leftEyesY;
    private Float rightEyesX;
    private Float rightEyesY;

    public Photo() {
    }

    public Photo(Long id) {
        this.id = id;
    }

    public Photo(Long id, String photoUrl, Float noiseX, Float noiseY, Float leftEyesX, Float leftEyesY, Float rightEyesX, Float rightEyesY) {
        this.id = id;
        this.photoUrl = photoUrl;
        this.noiseX = noiseX;
        this.noiseY = noiseY;
        this.leftEyesX = leftEyesX;
        this.leftEyesY = leftEyesY;
        this.rightEyesX = rightEyesX;
        this.rightEyesY = rightEyesY;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public Float getNoiseX() {
        return noiseX;
    }

    public void setNoiseX(Float noiseX) {
        this.noiseX = noiseX;
    }

    public Float getNoiseY() {
        return noiseY;
    }

    public void setNoiseY(Float noiseY) {
        this.noiseY = noiseY;
    }

    public Float getLeftEyesX() {
        return leftEyesX;
    }

    public void setLeftEyesX(Float leftEyesX) {
        this.leftEyesX = leftEyesX;
    }

    public Float getLeftEyesY() {
        return leftEyesY;
    }

    public void setLeftEyesY(Float leftEyesY) {
        this.leftEyesY = leftEyesY;
    }

    public Float getRightEyesX() {
        return rightEyesX;
    }

    public void setRightEyesX(Float rightEyesX) {
        this.rightEyesX = rightEyesX;
    }

    public Float getRightEyesY() {
        return rightEyesY;
    }

    public void setRightEyesY(Float rightEyesY) {
        this.rightEyesY = rightEyesY;
    }

}
