package grigoreva.facesmanager.data.greendao;

import grigoreva.facesmanager.data.greendaocustomtype.LandmarkType;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PHOTO_LANDMARK".
 */
public class PhotoLandmark {

    private Long id;
    private LandmarkType landmarkType;
    private Long photoId;
    private Float pointX;
    private Float pointY;
    private Float normPointX;
    private Float normPointY;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PhotoLandmark() {
    }

    public PhotoLandmark(Long id) {
        this.id = id;
    }

    public PhotoLandmark(Long id, LandmarkType landmarkType, Long photoId, Float pointX, Float pointY, Float normPointX, Float normPointY) {
        this.id = id;
        this.landmarkType = landmarkType;
        this.photoId = photoId;
        this.pointX = pointX;
        this.pointY = pointY;
        this.normPointX = normPointX;
        this.normPointY = normPointY;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LandmarkType getLandmarkType() {
        return landmarkType;
    }

    public void setLandmarkType(LandmarkType landmarkType) {
        this.landmarkType = landmarkType;
    }

    public Long getPhotoId() {
        return photoId;
    }

    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    public Float getPointX() {
        return pointX;
    }

    public void setPointX(Float pointX) {
        this.pointX = pointX;
    }

    public Float getPointY() {
        return pointY;
    }

    public void setPointY(Float pointY) {
        this.pointY = pointY;
    }

    public Float getNormPointX() {
        return normPointX;
    }

    public void setNormPointX(Float normPointX) {
        this.normPointX = normPointX;
    }

    public Float getNormPointY() {
        return normPointY;
    }

    public void setNormPointY(Float normPointY) {
        this.normPointY = normPointY;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
